[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/"
timeout = 300

[[build.watchPaths]]
paths = ["apps/web/**"]
