version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: luster
      POSTGRES_USER: luster
      POSTGRES_PASSWORD: luster_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luster -d luster"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: